/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dittmer.linr;

import org.junit.*;


public class AppTest {
    
    public AppTest() {}
    
    @Test
    public void testApp()
    {
        //Just to increase code coverage
        App.main(null);
    }
}
