/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linr;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.JFileChooser;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;


public class App {
    
    public static ArrayList<LineNote> lineNotes;
    public static File lineNotesFile;

    public static void main(String[] args) {
        //Create or find file
        File linrFile = new File(System.getProperty("user.home") + "/.linr");
        try {
            linrFile.mkdir();
        } catch (Exception e) {
            e.printStackTrace();
        }
        lineNotesFile = new File(linrFile, "notes.txt");
        
        //Initialize arraylist
        lineNotes = new ArrayList<>();

        //Read file if it exists
        try(BufferedReader br = new BufferedReader(new FileReader(lineNotesFile)))
        {
            String line;
            while((line = br.readLine()) != null)
            {
                lineNotes.add(LineNote.parse(line));
            }
        } catch (FileNotFoundException e) {} catch(IOException e) {}

        exportPDFs();

        //Write savefile and close
        BufferedWriter bw;
        try {
            bw = new BufferedWriter(new FileWriter(lineNotesFile));
            for(LineNote ln : lineNotes)
            {
                bw.write(ln.toString());
                bw.newLine();
            }
            bw.close();
        } 
        catch (IOException e) 
        {
            e.printStackTrace();
        }
        
    }

    public static void addPdfCellGrey(PdfPTable table, String value)
    {
        PdfPCell cell=new PdfPCell(new Phrase(value));
        cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
        cell.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
        table.addCell(cell);
    }

    public static void exportPDFs()
    {
        Map<String, List<LineNote>> lineNotesByActor = new HashMap<String, List<LineNote>>();
        for(LineNote ln : lineNotes)
        {
            if(ln == null)
                continue;

            
            if(!lineNotesByActor.keySet().contains(ln.actor))
            {
                lineNotesByActor.put(ln.actor, new ArrayList<LineNote>());
            }
            lineNotesByActor.get(ln.actor).add(ln);

        }
        //Open save window
        JFileChooser jfc = new JFileChooser(System.getProperty("user.home"));
        jfc.setDialogTitle("Select Export Folde");
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int jfcResult = jfc.showSaveDialog(null);
        if(jfcResult == JFileChooser.APPROVE_OPTION)
        {
            File exportDir = jfc.getSelectedFile();
            for(String actor : lineNotesByActor.keySet())
            {
                List<LineNote> lineNotes = lineNotesByActor.get(actor);
                try {
                    Document lineNoteDoc = new Document(PageSize.LETTER.rotate());
                    PdfWriter.getInstance(lineNoteDoc, new FileOutputStream(exportDir.getAbsolutePath() + "/" + actor + "LineNotes.pdf"));
                    lineNoteDoc.open();
                    lineNoteDoc.add(new Chunk("")); // << this will do the trick.             
                    PdfPTable lineNoteTable = new PdfPTable(7);
                    PdfPCell lineNoteTableCell;

                    //Add header row
                    addPdfCellGrey(lineNoteTable, "Scene");
                    addPdfCellGrey(lineNoteTable, "Page");
                    addPdfCellGrey(lineNoteTable, "Action");
                    addPdfCellGrey(lineNoteTable, "Line");
                    addPdfCellGrey(lineNoteTable, "Notes");
                    addPdfCellGrey(lineNoteTable, "Occurences");
                    addPdfCellGrey(lineNoteTable, "Fixed");
                    lineNoteTable.setHeaderRows(1);

                    List<String> allValues = new ArrayList<String>();
                    //Insert line note into table row
                    for (LineNote ln : lineNotes) 
                    {   
                        String[] lnValues = ln.toString().substring((actor.length())+1).split(",");
                        Collections.addAll(allValues, lnValues);                              
                    }
                    for(String value : allValues)
                    {
                        lineNoteTableCell=new PdfPCell(new Phrase(value));
                        lineNoteTable.addCell(lineNoteTableCell);
                    }
                    //Attach table to PDF and close the document
                    lineNoteDoc.add(lineNoteTable);                       
                    lineNoteDoc.close();
                } 
                catch (IOException e) 
                {
                    e.printStackTrace();
                }
                catch(DocumentException e)
                {
                    e.printStackTrace();
                }
            }
        }

    }
}
