/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linr;

import org.junit.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
       
    }
}
